# Generated by Django 4.2.4 on 2023-08-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_questionmodel_leve_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='leve_choice',
            new_name='level_choice',
        ),
    ]
