# Generated by Django 4.2.3 on 2023-08-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_answermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.questionmodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.categorymodel'),
        ),
    ]
