# Generated by Django 4.2.4 on 2023-08-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_answermodel_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='core.questionmodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to='core.categorymodel'),
        ),
        migrations.CreateModel(
            name='ResultQuiztModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_correct_answer', to='core.answermodel')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_quiz', to='core.quizmodel')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_selected_answer', to='core.answermodel')),
            ],
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='core.answermodel'),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category', to='core.categorymodel'),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='core.questionmodel'),
        ),
    ]
