# Generated by Django 4.2.4 on 2023-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quizmodel_options_quizmodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizmodel',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='resultquiztmodel',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='title',
            field=models.CharField(default='Quiz Temporary', max_length=255, verbose_name='Title'),
        ),
    ]
