# Generated by Django 4.2.4 on 2023-08-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quizmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultquiztmodel',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_correct_answer', to='core.quizmodel'),
        ),
    ]
