# Generated by Django 4.2.4 on 2023-08-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resultquiztmodel_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='correct_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer', to='core.answermodel'),
        ),
        migrations.DeleteModel(
            name='ResultQuiztModel',
        ),
    ]
