# Generated by Django 4.2.4 on 2023-08-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quizmodel_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='end_time',
            new_name='total_time',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='start_time',
        ),
    ]
