# Generated by Django 4.2.4 on 2023-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_quizmodel_point_alter_quizmodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='total_time',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Time'),
        ),
    ]
