# Generated by Django 4.2.4 on 2023-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_quizmodel_total_time_quizmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizmodel',
            old_name='time',
            new_name='total_time',
        ),
    ]
