# Generated by Django 4.2.4 on 2023-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_time_quizmodel_total_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='level_choice',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='total_time',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Time'),
        ),
    ]
