# Generated by Django 4.2.4 on 2023-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='total_time',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Time'),
        ),
    ]
